name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Log in to the Github Container registry'
        uses: 'docker/login-action@v3'
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Generate a Release Tag'
        working-directory: ${{ env.ADGUARDHOME_BUILD_PATH }}
        id: build-version
        run: |
          echo "build_date=$( date -u +'%Y-%m-%dT%H:%M:%SZ' )" >> $GITHUB_ENV
      
      - name: 'Build & Publish Docker Image'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          outputs: type=image
          platforms: linux/amd64, linux/arm64
          # build-args: |
              # NONE=${{ env.NONE }}
          labels: |
            maintainer=${{ github.actor }}
            org.opencontainers.image.created=${{ env.build_date }}
            org.opencontainers.image.description=Docker in Docker with node
            org.opencontainers.image.licenses=GPL-3.0
            org.opencontainers.image.source=https://github/${{ github.repository }}
            org.opencontainers.image.title=dind-node
            org.opencontainers.image.url=https://github/${{ github.repository }}
            org.opencontainers.image.version=1.0
          tags: |
            ghcr.io/${{ github.repository }}:latest
